# Generated by Django 4.2.7 on 2023-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='standard_or_semester',
            field=models.IntegerField(),
        ),
    ]
