# Generated by Django 4.2.7 on 2023-11-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_teacher_standard_or_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='standard_or_semester',
            field=models.IntegerField(),
        ),
    ]
