# Generated by Django 4.2.7 on 2023-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sessionrequest_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
