# Generated by Django 4.2.7 on 2023-12-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
