# Generated by Django 4.2.7 on 2023-12-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_sessionrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
