# Generated by Django 4.2.7 on 2024-01-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sessionrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='message',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
