# Generated by Django 4.2.7 on 2023-11-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sessionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to='home.student'),
        ),
        migrations.AlterField(
            model_name='sessionrequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='home.teacher'),
        ),
    ]
