# Generated by Django 4.2.7 on 2023-11-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_sessionrequest_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='sessionrequest',
            name='time',
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
