# Generated by Django 4.2.7 on 2023-11-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_sessionrequest_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
