# Generated by Django 4.2.7 on 2023-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_sessionrequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrequest',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
