# Generated by Django 4.2.7 on 2023-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionrequest',
            name='requested_cost',
            field=models.IntegerField(default=0),
        ),
    ]
